export const context = {
  include_headers: '',
  RivuletStream: 'RivuletStream*',
  periodic: 'rivulet_stream_periodic',
  empty: 'rivulet_stream_empty_create',
  never: 'rivulet_stream_never_create',
  'Rivulet<Int>': 'RivuletStream*',
  IntStream: 'RivuletStream*',
  number: 'int',
  Int: 'int',
  map: 'rivulet_stream_map',
  mapTo: 'rivulet_stream_map_to',
  filter: 'rivulet_stream_filter',
  take: 'rivulet_stream_take',
  drop: 'rivulet_stream_drop',
  last: 'rivulet_stream_last',
  sample: 'rivulet_stream_sample',
  delay: 'rivulet_stream_delay',
};
